version: '3'
services:
  ldapserver:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/workspace:cached
        - /var/run/docker.sock:/var/run/docker-host.sock
      command: /bin/sh -c "while sleep 1000; do :; done"
