name: Build Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build
      run: dotnet build --configuration Release Sample/Sample.csproj
    - name: Install ldapsearch
      run: sudo apt-get -y install ldap-utils
    - name: Test
      run: dotnet test Sample.Tests/
